"""Supplies table added

Revision ID: 006836264df9
Revises: 4bcc5210adcf
Create Date: 2023-02-16 21:26:06.202842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006836264df9'
down_revision = '4bcc5210adcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maxBuying', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_supply_product_id_product'), 'product', ['product_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_supply_job_id_job'), 'job', ['job_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_supply_maxBuying_price'), 'price', ['maxBuying'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_supply_maxBuying_price'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_supply_job_id_job'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_supply_product_id_product'), type_='foreignkey')
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('job_id')
        batch_op.drop_column('product_id')
        batch_op.drop_column('total')
        batch_op.drop_column('maxBuying')

    # ### end Alembic commands ###
