"""Job Model Added

Revision ID: 458a53dc962d
Revises: b91d32ffe03a
Create Date: 2023-02-14 21:55:57.306191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458a53dc962d'
down_revision = 'b91d32ffe03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lpo', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cheque', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('client', sa.Integer(), nullable=False))
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_job_client_company'), 'company', ['client'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_job_client_company'), type_='foreignkey')
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('client')
        batch_op.drop_column('cheque')
        batch_op.drop_column('lpo')

    # ### end Alembic commands ###
