"""Job Model updated

Revision ID: 4bcc5210adcf
Revises: 458a53dc962d
Create Date: 2023-02-14 22:13:19.386541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcc5210adcf'
down_revision = '458a53dc962d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_job_client_company', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_job_client_id_company'), 'company', ['client_id'], ['id'])
        batch_op.drop_column('client')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_job_client_id_company'), type_='foreignkey')
        batch_op.create_foreign_key('fk_job_client_company', 'company', ['client'], ['id'])
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
