"""Initial migration.

Revision ID: f6d115450664
Revises: 
Create Date: 2023-01-26 13:44:40.323762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d115450664'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_person_company_id_company'), 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_person_company_id_company'), type_='foreignkey')
        batch_op.drop_column('company_id')
        batch_op.drop_column('email')
        batch_op.drop_column('contact')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
